todos os metodos criados
analuijesus/rchlo1-back-sprint1 pull request #1
Opened 2021-11-29 15:05 UTC by analuijesus

2021-11-29 16:34 UTC, alexandreaquiles requested changes
Opa, @analuijesus 

Está quase perfeito!

Acho que tem uns 3 detalhes pra mudar que comentei na PR!

2021-11-29 16:34 UTC, alexandreaquiles commented on src/main/java/br/com/rchlo/test/TestaMetodosProdutos.java
> +    }
Aqui, você retornou a lista dos produtos de um determinado tamanho.

Na verdade, o que precisamos é algo que mostre cada tamanho com a lista de produtos que têm aquele tamanho.

Por exemplo:

PEQUENO -> Camiseta Azul,  Blusa Moletom, Camiseta Branca, Regata
MEDIO -> Camiseta Azul,  Blusa Moletom, Camiseta Branca, Regata
GRANDE -> Jaqueta, Blusa Moletom, Regata
EXTRA_GRANDE -> Jaqueta

O retorno do método deve ser um `Map <Tamanho, List<Produto>>`

2021-11-29 16:34 UTC, alexandreaquiles commented on src/main/java/br/com/rchlo/test/TestaMetodosProdutos.java
> +    }
Aqui, você fez a quantidade de produtos de uma determinada cor.

Na verdade, queremos as cores associadas com a quantidade de produtos daquela cor.

Algo como:
 BRANCA -> 3
 VERMELHA -> 1
 AZUL -> 1
 PRETA -> 0
 CINZA -> 0
 ROSA -> 0
 VERDE -> 0
 
O retorno do método deve ser um: `Map <Cor, Integer>`.

2021-11-29 16:34 UTC, alexandreaquiles commented on src/main/java/br/com/rchlo/test/TestaMetodosProdutos.java
> +        System.out.println(produtoComMenorDesconto);
A ideia aqui é mostrar só o preço!

2021-11-29 20:50 UTC, alexandreaquiles approved these changes
Opa! Como você me disse, já estava sendo feito o que tinha falado. Foi mal! hehe

2021-11-30 00:38 UTC, mariasantosdev approved these changes

2021-11-30 00:38 UTC, mariasantosdev commented on src/main/java/br/com/rchlo/test/TestaMetodosProdutos.java
> +    private static Map<Tamanho, List<Produto>> exibeTamanhoDeCadaProduto() {
Não tenho certeza se os nomes dos métodos estão semânticos.... Acredito que esses métodos busquem alguma informação e não exigem.....
poderia ser `buscaTamanhoDeCadaProduto`

2021-11-30 00:38 UTC, mariasantosdev commented on src/main/java/br/com/rchlo/test/TestaMetodosProdutos.java
> +    private static Map<Tamanho, List<Produto>> exibeTamanhoDeCadaProduto() {
Vale para todos os outros métodos que não tenham o  System.out.println

2021-12-01 10:42 UTC, hopesoh approved these changes

2021-12-01 18:21 UTC, merged